version: '3.8'

services:
  mongo:
    image: mongo:7
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${DASHBOARD_HOSTNAME}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all

  redis:
    image: redis:7.2
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${DASHBOARD_HOSTNAME}
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --bind 0.0.0.0 --appendonly yes # enable persistence using AOF

  dashboard:
    image: ${DOCKER_REGISTRY}/shadow-dashboard:amd64
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${DASHBOARD_HOSTNAME}
    ports:
      - 8080:8080
    volumes:
      - processor_data_nfs:/usr/src/app/processor-common-folder
    environment:
      # - DEBUG=http,express:*
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - SHARED_FOLDER=processor-common-folder # path from app
    command: npm start

  evaluator:
    image: ${DOCKER_REGISTRY}/shadow-evaluator:amd64
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1 # only one evaluator per node
    volumes:
      - processor_data_nfs:/app/processor-common-folder
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_JOB_NOTIFY_CHANNEL=REDIS_JOB_NOTIFY_CHANNEL
      - SHARED_FOLDER=processor-common-folder # path from app
      - SYSTEM_HOSTNAME="{{.Node.Hostname}}" # this is the hostname of the node the container is running on
volumes:
  processor_data_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER_IP},rw,nfsvers=4
      device: ':/vol/vol1_home/docker/docker-swarm-volumes/processor-common-folder'
  redis-data:
    driver: local # this is a local volume, not on NFS
  mongo-data:
    driver: local # this is a local volume, not on NFS
