---
experiment_name: "example_vpn_small"
DEBUG: True
window: "1 seconds" # cache size but maybe smaller
tda: False
multiISP: True
# Scopes will be proccessed in order. Ensure order takes path most likely for
# communication
scope_config:
  - [".*isp-1.csv", "ISP1", none, [True, False]]
  - ["(.*root).*.csv", "root", dot_filter, [True, True] ]
server_logs: [".*pythonServerThread.stdout", "chatlogs"]
evil_domain: 'evil.dne'
bad_features: ['tcp.srcport', 'udp.srcport', 'tcp.seq',
                'frame.number', 'frame.time_relative', 'frame.time_delta']
output_file: "output.csv"
num_cpus: 16
skip: 1
dim: 0
tda_window: 3
k: 9
thresh: "inf"
# Optional
# Will be removed from search
infra_ip: ['192.168.150.10', '101.0.0.10', '101.0.0.20', '172.20.0.1', '172.20.0.10', '172.20.0.11', '172.20.0.12', '172.21.0.10', '172.21.0.1']
